namespace: platform-app

env:
  registryCreds: docker-hub-credentials
  helmChart: https://github.com/Evgeny-Nik/project_platform_app/raw/main/charts/deploying_chart/my-app-chart-1.0.0.tgz
  flaskSessionKey: your_secret_key
  redisHostUrl: redis-master.redis.svc.cluster.local
  redisHostPort: 6379
  redisPasswordSecretName: redis-password
  redisPasswordSecretKey: REDIS_HOST_PASSWORD

serviceAccount:
  name: platform-app-service-account

clusterRole:
  name: platform-app-cluster-role

clusterRoleBinding:
  name: platform-app-cluster-role-binding

deployment:
  name: platform-app
  replicas: 1
  appLabel: plaform-app
  imagePullPolicy: IfNotPresent
  container:
    name: plaform-app
    image: evgenyniko/platform_app
    tag: 1.0.6
    port: 8000

service:
  name: http
  port: 8000
  protocol: TCP
  targetPort: 8000
  type: ClusterIP

ingress:
  className: alb
  host: example.com
  path: /
  pathType: Prefix
  alb:
    scheme: internet-facing
    targetType: ip
    groupName: dev-team

kubernetesClusterDomain: cluster.local
