apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.appLabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.appLabel }}
    spec:
      containers:
      - name: {{ .Values.deployment.container.name }}
        image: {{ .Values.deployment.container.image }}:{{ .Values.deployment.container.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.deployment.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.deployment.container.port }}
