apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.deployment.name }}-ingress
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.deployment.appLabel }}
  annotations:
    alb.ingress.kubernetes.io/scheme: {{ .Values.ingress.alb.scheme }}
    alb.ingress.kubernetes.io/target-type: {{ .Values.ingress.alb.targetType }}
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.ingress.alb.certificateArn | default (lookup "v1" "Secret" .Values.namespace "cert-arn-secret").data.CERTIFICATE_ARN | b64dec }}
    alb.ingress.kubernetes.io/listen-ports: {{ .Values.ingress.alb.listenPorts }}
    alb.ingress.kubernetes.io/ssl-redirect: {{ .Values.ingress.alb.ssl-redirect }}
    alb.ingress.kubernetes.io/group.name: {{ .Values.ingress.alb.groupName }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Release.Namespace }}.{{ .Values.ingress.host }}
      http:
        paths:
          - path: { { .Values.ingress.path } }
            pathType: { { .Values.ingress.pathType } }
            backend:
              service:
                name: {{ .Values.deployment.name }}-service
                port:
                  number: {{ .Values.service.port }}
